- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Skip this
      debug:
        msg: "This message should be skipped"
      when: False